FROM node:18 as setup

WORKDIR /app

# setup api-server
FROM setup as build_web_server

WORKDIR /app/web_server

COPY ./package.json .
COPY ./yarn.lock .

RUN yarn

COPY ./ .

EXPOSE 3000

CMD ["yarn", "start:prod"]