FROM node:18 as setup

WORKDIR /app

# setup api-server
FROM setup as build_web_server

WORKDIR /app/web_server

COPY ./package.json .
COPY ./yarn.lock .

RUN yarn

COPY ./ .

EXPOSE 3000

# TODO: intead of just running "node", run pm2 to benefit from clustering
# example command: pm2 start yarn --interpreter bash --name simple-app-server -- start:prod
CMD ["yarn", "start:prod"]